[pytest]

# 'pythonpath' no es una opción nativa de pytest.
# Solo funciona si está instalado el plugin
# 'pytest-pythonpath'. En este proyecto no es
# necesario, ya que 'tests/conftest.py' añade
# automáticamente la carpeta 'src' al PYTHONPATH.
# pythonpath = src

testpaths = tests
