name: Build Windows

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check Python
        run: |
          python --version
          where.exe python

      - name: Create virtual environment
        run: |
          python -m venv .venv

      - name: Activate and check virtual environment
        run: |
          .\.venv\Scripts\Activate.ps1
          python --version
          where.exe python
          where.exe pip

      - name: Upgrade pip
        run: |
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          .\.venv\Scripts\Activate.ps1
          pip install -r requirements.txt

      - name: Build
        run: |
          .\.venv\Scripts\Activate.ps1
          python .\compile\windows\build.py

      - name: Check executable
        run: |
          Get-Item .\dist\GeiMesDB.exe

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: GeiMesDB-windows
          path: dist/GeiMesDB.exe
